services:
  oracle-xe:
    image: gvenzl/oracle-xe:latest
    platform: linux/amd64
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_DATABASE: ${ORACLE_DATABASE}
    ports:
      - "${ORACLE_PORT}:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

  minio:
    image: minio/minio:latest
    platform: linux/amd64
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000" # S3 API
      - "${MINIO_CONSOLE_PORT}:9001" # Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    volumes:
      - minio-data:/opt/minio/data

volumes:
  oracle-data:
  minio-data:
